spring:
  application:
    name: vaksine
  datasource:
    url:jdbc:h2:mem:vaksine
    username:root
    password:123
    driverClassName:org.h2.Driver
  jpa:
    database-platform:org.hibernet.dialect.H2Dialect
